// vocabulary-data.js
const vocabularyUnits = {
    "英数字": [
      { japanese: "16進数", furigana: "16しんすう", english: "hexadecimal", chinese: "16进制", traditional: "16進制" },
      { japanese: "2進数", furigana: "2しんすう", english: "binary", chinese: "二进制", traditional: "二進制" },
      { japanese: "2相コミット", furigana: "2そうコミット", english: "two-phase commit", chinese: "二阶段提交", traditional: "二階段提交" },
      { japanese: "8進数", furigana: "8しんすう", english: "octal", chinese: "8进制", traditional: "8進制" },
      { japanese: "BNF記法", furigana: "BNFきほう", english: "Backus-Naur form、BNF", chinese: "巴科斯范式", traditional: "巴科斯範式" },
      { japanese: "B木", furigana: "Bき", english: "B-tree", chinese: "B树", traditional: "B樹" },
      { japanese: "DNSキャッシュポイズニング", furigana: "DNSキャッシュポイズニング", english: "DNS cache poisoning、DNS cache pollution", chinese: "域名服务器缓存投毒、DNS缓存投毒、DNS污染", traditional: "域名服務器緩存投毒、DNS緩存投毒、DNS污染" },
      { japanese: "E-R図", furigana: "E-Rず", english: "entity-relationship model", chinese: "ER模型、实体联系模型", traditional: "ER模型、實體聯繫模型" },
      { japanese: "IPアドレス", furigana: "IPアドレス", english: "IP address", chinese: "IP地址", traditional: "IP地址" },
      { japanese: "IPマスカレード", furigana: "IPマスカレード", english: "IP masquerade", chinese: "IP伪装", traditional: "IP偽裝" },
      { japanese: "SEOポイズニング", furigana: "SEOポイズニング", english: "SEO poisoning", chinese: "SEO中毒", traditional: "SEO中毒" },
      { japanese: "SQLインジェクション", furigana: "SQLインジェクション", english: "SQL injection", chinese: "SQL注入、SQL注码", traditional: "SQL注入、SQL注碼" },
      { japanese: "CAPTCHA", furigana: "キャプチャ", english: "CAPTCHA", chinese: "验证码", traditional: "驗證碼" },
      { japanese: "SOAP", furigana: "ソープ", english: "simple object access protocol、SOAP", chinese: "简单对象访问协议", traditional: "簡單對象訪問協議" }
    ],
    "あ行": [
      { japanese: "アーンドバリューマネジメント", furigana: "アーンドバリューマネジメント", english: "earned value management、 EVM", chinese: "挣值管理", traditional: "掙值管理" },
      { japanese: "アカウント", furigana: "アカウント", english: "account", chinese: "账户", traditional: "賬戶" },
      { japanese: "アクション", furigana: "アクション", english: "action", chinese: "动作", traditional: "動作" },
      { japanese: "アクセス", furigana: "アクセス", english: "access", chinese: "访问", traditional: "訪問" },
      { japanese: "アクセスレベル", furigana: "アクセスレベル", english: "access level", chinese: "访问级别", traditional: "訪問級別" },
      { japanese: "アクティビティ", furigana: "アクティビティ", english: "activity", chinese: "活动", traditional: "活動" },
      { japanese: "アクティブ", furigana: "アクティブ", english: "activate", chinese: "激活", traditional: "激活" },
      { japanese: "アダプタ", furigana: "アダプタ", english: "adapter", chinese: "适配器", traditional: "適配器" },
      { japanese: "アプリケーション", furigana: "アプリケーション", english: "application", chinese: "应用、应用程序", traditional: "應用、應用程序" },
      { japanese: "アプリケーション層", furigana: "アプリケーションそう", english: "application layer", chinese: "应用层", traditional: "應用層" },
      { japanese: "アルゴリズム", furigana: "アルゴリズム", english: "algorithm", chinese: "算法", traditional: "算法" },
      { japanese: "暗号化", furigana: "あんごうか", english: "encryption", chinese: "加密", traditional: "加密" },
      { japanese: "アンチエイリアシング", furigana: "アンチエイリアシング", english: "anti-aliasing", chinese: "反锯齿", traditional: "反鋸齒" },
      { japanese: "イテレーション", furigana: "イテレーション", english: "iteration", chinese: "迭代", traditional: "迭代" },
      { japanese: "イテレータ", furigana: "イテレータ", english: "iterator", chinese: "迭代器", traditional: "迭代器" },
      { japanese: "イベント", furigana: "イベント", english: "event", chinese: "事件", traditional: "事件" },
      { japanese: "インシデント", furigana: "インシデント", english: "incident", chinese: "事件", traditional: "事件" },
      { japanese: "ウィンドウ", furigana: "ウィンドウ", english: "window", chinese: "窗口", traditional: "窗口" },
      { japanese: "エクスプロイトコード", furigana: "エクスプロイトコード", english: "exploit code", chinese: "漏洞利用代码", traditional: "漏洞利用代碼" },
      { japanese: "エッジ", furigana: "エッジ", english: "edge", chinese: "边", traditional: "邊" },
      { japanese: "エラーメッセージ", furigana: "エラーメッセージ", english: "error message", chinese: "报错", traditional: "報錯" },
      { japanese: "エラーログ", furigana: "エラーログ", english: "error log", chinese: "错误日志", traditional: "錯誤日誌" },
      { japanese: "エンジン", furigana: "エンジン", english: "engine", chinese: "引擎", traditional: "引擎" },
      { japanese: "エンタープライズアーキテクチャ", furigana: "エンタープライズアーキテクチャ", english: "enterprise architecture、 EA", chinese: "企业架构", traditional: "企業架構" },
      { japanese: "エンドツーエンド認証", furigana: "エンドツーエンドにんしょう", english: "end-to-end authentication", chinese: "端对端身份验证", traditional: "端對端身份驗證" },
      { japanese: "オートマトン", furigana: "オートマトン", english: "automaton", chinese: "自动机", traditional: "自動機" },
      { japanese: "オーバーライド", furigana: "オーバーライド", english: "override", chinese: "覆写、重新定义", traditional: "覆寫、重新定義" },
      { japanese: "オーバーロード", furigana: "オーバーロード", english: "overload", chinese: "重载", traditional: "重載" },
      { japanese: "オペレーティングシステム", furigana: "オペレーティングシステム", english: "operating system 、OS", chinese: "操作系统", traditional: "操作系統" }
    ],
    "か行": [
      { japanese: "カーネル", furigana: "カーネル", english: "kernel", chinese: "内核", traditional: "內核" },
      { japanese: "仮想記憶", furigana: "かそうきおく", english: "virtual memory", chinese: "虚拟内存", traditional: "虛擬內存" },
      { japanese: "カルノー図", furigana: "カルノーず", english: "Karnaugh map", chinese: "卡诺图", traditional: "卡諾圖" },
      { japanese: "簡易メール転送プロトコル", furigana: "かんいメールてんそうプロトコル", english: "simple mail transfer protocol、SMTP", chinese: "简单邮件传输协议", traditional: "簡單郵件傳輸協議" },
      { japanese: "関係データベース", furigana: "かんけいデータベース", english: "relational database", chinese: "关系数据库", traditional: "關係數據庫" },
      { japanese: "キー", furigana: "キー", english: "key", chinese: "键", traditional: "鍵" },
      { japanese: "キーバリューストア", furigana: "キーバリューストア", english: "key–value store、KVS", chinese: "键值数据库、键值存储", traditional: "鍵值數據庫、鍵值存儲" },
      { japanese: "機械学習", furigana: "きかいがくしゅう", english: "machine learning", chinese: "机器学习", traditional: "機器學習" },
      { japanese: "逆ポーランド記法", furigana: "ぎゃくポーランドきほう", english: "reverse polish notation、RPN", chinese: "逆波兰表示法、逆波兰记法", traditional: "逆波蘭表示法、逆波蘭記法" },
      { japanese: "キャッシュサーバ", furigana: "キャッシュサーバ", english: "cache server", chinese: "缓存服务器", traditional: "緩存服務器" },
      { japanese: "キャパシティ", furigana: "キャパシティ", english: "capacity", chinese: "容量", traditional: "容量" },
      { japanese: "近似文字列照合", furigana: "きんじちもじれつしょうごう", english: "approximate string matching", chinese: "字符串模糊匹配", traditional: "字符串模糊匹配" },
      { japanese: "クライアント", furigana: "クライアント", english: "client", chinese: "客户、客户端", traditional: "客戶、客戶端" }
    ],
    "さ行": [
  { japanese: "サーバ", furigana: "サーバ", english: "server", chinese: "服务器", traditional: "服務器" },
  { japanese: "再帰", furigana: "さいき", english: "recursion", chinese: "递归", traditional: "遞歸" },
  { japanese: "最初適合アルゴリズム", furigana: "さいしょてきごうアルゴリズム", english: "first fit algorithm", chinese: "首次适应算法", traditional: "首次適應算法" },
  { japanese: "最短経路", furigana: "さいたんけいろ", english: "shortest path", chinese: "最短路径", traditional: "最短路徑" },
  { japanese: "最良適合アルゴリズム", furigana: "さいりょうてきごうアルゴリズム", english: "best fit algorithm", chinese: "最佳适应算法", traditional: "最佳適應算法" },
  { japanese: "作成", furigana: "さくせい", english: "create/creation", chinese: "创建、生成", traditional: "創建、生成" },
  { japanese: "サブクエリ", furigana: "サブクエリ", english: "subquery", chinese: "子查询", traditional: "子查詢" },
  { japanese: "サブネットアドレス", furigana: "サブネットアドレス", english: "subnet address", chinese: "子网地址", traditional: "子網地址" },
  { japanese: "サブネットマスク", furigana: "サブネットマスク", english: "sub-net mask", chinese: "子网掩码", traditional: "子網掩碼" },
  { japanese: "サンドボックス", furigana: "サンドボックス", english: "sandbox", chinese: "沙盒", traditional: "沙盒" },
  { japanese: "実コスト", furigana: "じつコスト", english: "actual cost", chinese: "实际成本", traditional: "實際成本" },
  { japanese: "冗長構成", furigana: "じょうちょうこうせい", english: "redundant configuration", chinese: "冗余配置", traditional: "冗餘配置" },
  { japanese: "情報セキュリティ", furigana: "じょうほうセキュリティ", english: "information security", chinese: "信息安全", traditional: "信息安全" },
  { japanese: "初期化", furigana: "しょきか", english: "initialization", chinese: "初始化", traditional: "初始化" },
  { japanese: "初期化リスト", furigana: "しょきかリスト", english: "initialization list", chinese: "初始化列表、初始值列表", traditional: "初始化列表、初始值列表" },
  { japanese: "シンクライアント", furigana: "シンクライアント", english: "thin client", chinese: "瘦客户端", traditional: "瘦客戶端" },
  { japanese: "人工ニューラルネットワーク", furigana: "じんこうニューラルネットワーク", english: "artificial neural network、ANN", chinese: "人工神经网络", traditional: "人工神經網絡" },
  { japanese: "スイッチングハブ", furigana: "スイッチングハブ", english: "switching hub", chinese: "网络交换机", traditional: "網絡交換機" },
  { japanese: "スーパースカラ", furigana: "スーパースカラ", english: "superscalar", chinese: "超标量", traditional: "超標量" },
  { japanese: "スキーム", furigana: "スキーム", english: "scheme", chinese: "框架", traditional: "框架" },
  { japanese: "スタックポインタ", furigana: "スタックポインタ", english: "stack pointer", chinese: "堆栈指针", traditional: "堆棧指針" },
  { japanese: "スタック領域", furigana: "スタックりょういき", english: "stack memory", chinese: "栈内存", traditional: "棧內存" },
  { japanese: "スタブ", furigana: "スタブ", english: "stub", chinese: "桩", traditional: "樁" },
  { japanese: "ストアドプロシージャ", furigana: "ストアドプロシージャ", english: "stored procedure", chinese: "存储过程", traditional: "存儲過程" },
  { japanese: "ストリング", furigana: "ストリング", english: "string", chinese: "字符串", traditional: "字符串" },
  { japanese: "スラッシング", furigana: "スラッシング", english: "thrashing", chinese: "颠簸", traditional: "顛簸" },
  { japanese: "セッション", furigana: "セッション", english: "session", chinese: "会话", traditional: "會話" },
  { japanese: "セマフォ", furigana: "セマフォ", english: "semaphore", chinese: "信号标", traditional: "信號標" },
  { japanese: "ゼロディ攻撃", furigana: "ゼロディこうげき", english: "zero-day attack", chinese: "零日攻击", traditional: "零日攻擊" },
  { japanese: "ソースコード", furigana: "ソースコード", english: "source code", chinese: "源码、源代码", traditional: "源碼、源代碼" }
],
"た行": [
  { japanese: "帯域圧縮", furigana: "たいいきあっしゅく", english: "bandwidth reduction", chinese: "带宽压缩", traditional: "帶寬壓縮" },
  { japanese: "帯域幅", furigana: "たいいきはば", english: "bandwidth", chinese: "带宽", traditional: "帶寬" },
  { japanese: "耐タンパー性", furigana: "たいタンパせい", english: "tamper resistant", chinese: "防篡改", traditional: "防篡改" },
  { japanese: "ダイヤルアップ", furigana: "ダイヤルアップ", english: "dial up", chinese: "拨号", traditional: "撥號" },
  { japanese: "タスク", furigana: "タスク", english: "task", chinese: "任务", traditional: "任務" },
  { japanese: "ダミー作業", furigana: "ダミーさぎょう", english: "dummy work", chinese: "虚拟工作", traditional: "虛擬工作" },
  { japanese: "ディープラーニング", furigana: "ディープラーニング", english: "deep learning", chinese: "深度学习", traditional: "深度學習" },
  { japanese: "ディザリング", furigana: "ディザリング", english: "dithering", chinese: "抖动", traditional: "抖動" },
  { japanese: "ディジタルシグナルプロセッサ", furigana: "ディジタルシグナルプロセッサ", english: "digital signal processor", chinese: "数字信号处理器", traditional: "數字信號處理器" },
  { japanese: "ディレクトリトラバーサル攻撃", furigana: "ディレクトリトラバーサルこうげき", english: "directory traversal attack", chinese: "目录遍历攻击", traditional: "目錄遍歷攻擊" },
  { japanese: "データ", furigana: "データ", english: "data", chinese: "数据", traditional: "數據" },
  { japanese: "データ構造", furigana: "データこうぞう", english: "data structures", chinese: "数据结构", traditional: "數據結構" },
  { japanese: "データ辞書", furigana: "データじしょ", english: "data dictionary", chinese: "数据字典", traditional: "數據字典" },
  { japanese: "データセット", furigana: "データセット", english: "dataset", chinese: "数据集", traditional: "數據集" },
  { japanese: "データベース", furigana: "データベース", english: "database", chinese: "数据库", traditional: "數據庫" }
],
  "さ行": [
    { japanese: "サーバ", furigana: "サーバ", english: "server", chinese: "服务器", traditional: "服務器" },
    { japanese: "再帰", furigana: "さいき", english: "recursion", chinese: "递归", traditional: "遞歸" },
    { japanese: "最初適合アルゴリズム", furigana: "さいしょてきごうアルゴリズム", english: "first fit algorithm", chinese: "首次适应算法", traditional: "首次適應算法" },
    { japanese: "最短経路", furigana: "さいたんけいろ", english: "shortest path", chinese: "最短路径", traditional: "最短路徑" },
    { japanese: "最良適合アルゴリズム", furigana: "さいりょうてきごうアルゴリズム", english: "best fit algorithm", chinese: "最佳适应算法", traditional: "最佳適應算法" },
    { japanese: "作成", furigana: "さくせい", english: "create/creation", chinese: "创建、生成", traditional: "創建、生成" },
    { japanese: "サブクエリ", furigana: "サブクエリ", english: "subquery", chinese: "子查询", traditional: "子查詢" },
    { japanese: "サブネットアドレス", furigana: "サブネットアドレス", english: "subnet address", chinese: "子网地址", traditional: "子網地址" },
    { japanese: "サブネットマスク", furigana: "サブネットマスク", english: "sub-net mask", chinese: "子网掩码", traditional: "子網掩碼" },
    { japanese: "サンドボックス", furigana: "サンドボックス", english: "sandbox", chinese: "沙盒", traditional: "沙盒" },
    { japanese: "実コスト", furigana: "じつコスト", english: "actual cost", chinese: "实际成本", traditional: "實際成本" },
    { japanese: "冗長構成", furigana: "じょうちょうこうせい", english: "redundant configuration", chinese: "冗余配置", traditional: "冗餘配置" },
    { japanese: "情報セキュリティ", furigana: "じょうほうセキュリティ", english: "information security", chinese: "信息安全", traditional: "信息安全" },
    { japanese: "初期化", furigana: "しょきか", english: "initialization", chinese: "初始化", traditional: "初始化" },
    { japanese: "初期化リスト", furigana: "しょきかリスト", english: "initialization list", chinese: "初始化列表、初始值列表", traditional: "初始化列表、初始值列表" },
    { japanese: "シンクライアント", furigana: "シンクライアント", english: "thin client", chinese: "瘦客户端", traditional: "瘦客戶端" },
    { japanese: "人工ニューラルネットワーク", furigana: "じんこうニューラルネットワーク", english: "artificial neural network、ANN", chinese: "人工神经网络", traditional: "人工神經網絡" },
    { japanese: "スイッチングハブ", furigana: "スイッチングハブ", english: "switching hub", chinese: "网络交换机", traditional: "網絡交換機" },
    { japanese: "スーパースカラ", furigana: "スーパースカラ", english: "superscalar", chinese: "超标量", traditional: "超標量" },
    { japanese: "スキーム", furigana: "スキーム", english: "scheme", chinese: "框架", traditional: "框架" },
    { japanese: "スタックポインタ", furigana: "スタックポインタ", english: "stack pointer", chinese: "堆栈指针", traditional: "堆棧指針" },
    { japanese: "スタック領域", furigana: "スタックりょういき", english: "stack memory", chinese: "栈内存", traditional: "棧內存" },
    { japanese: "スタブ", furigana: "スタブ", english: "stub", chinese: "桩", traditional: "樁" },
    { japanese: "ストアドプロシージャ", furigana: "ストアドプロシージャ", english: "stored procedure", chinese: "存储过程", traditional: "存儲過程" },
    { japanese: "ストリング", furigana: "ストリング", english: "string", chinese: "字符串", traditional: "字符串" },
    { japanese: "スラッシング", furigana: "スラッシング", english: "thrashing", chinese: "颠簸", traditional: "顛簸" },
    { japanese: "セッション", furigana: "セッション", english: "session", chinese: "会话", traditional: "會話" },
    { japanese: "セマフォ", furigana: "セマフォ", english: "semaphore", chinese: "信号标", traditional: "信號標" },
    { japanese: "ゼロディ攻撃", furigana: "ゼロディこうげき", english: "zero-day attack", chinese: "零日攻击", traditional: "零日攻擊" },
    { japanese: "ソースコード", furigana: "ソースコード", english: "source code", chinese: "源码、源代码", traditional: "源碼、源代碼" }
  ],
  "た行": [
    { japanese: "帯域圧縮", furigana: "たいいきあっしゅく", english: "bandwidth reduction", chinese: "带宽压缩", traditional: "帶寬壓縮" },
    { japanese: "帯域幅", furigana: "たいいきはば", english: "bandwidth", chinese: "带宽", traditional: "帶寬" },
    { japanese: "耐タンパー性", furigana: "たいタンパせい", english: "tamper resistant", chinese: "防篡改", traditional: "防篡改" },
    { japanese: "ダイヤルアップ", furigana: "ダイヤルアップ", english: "dial up", chinese: "拨号", traditional: "撥號" },
    { japanese: "タスク", furigana: "タスク", english: "task", chinese: "任务", traditional: "任務" },
    { japanese: "ダミー作業", furigana: "ダミーさぎょう", english: "dummy work", chinese: "虚拟工作", traditional: "虛擬工作" },
    { japanese: "ディープラーニング", furigana: "ディープラーニング", english: "deep learning", chinese: "深度学习", traditional: "深度學習" },
    { japanese: "ディザリング", furigana: "ディザリング", english: "dithering", chinese: "抖动", traditional: "抖動" },
    { japanese: "ディジタルシグナルプロセッサ", furigana: "ディジタルシグナルプロセッサ", english: "digital signal processor", chinese: "数字信号处理器", traditional: "數字信號處理器" },
    { japanese: "ディレクトリトラバーサル攻撃", furigana: "ディレクトリトラバーサルこうげき", english: "directory traversal attack", chinese: "目录遍历攻击", traditional: "目錄遍歷攻擊" },
    { japanese: "データ", furigana: "データ", english: "data", chinese: "数据", traditional: "數據" },
    { japanese: "データ構造", furigana: "データこうぞう", english: "data structures", chinese: "数据结构", traditional: "數據結構" },
    { japanese: "データ辞書", furigana: "データじしょ", english: "data dictionary", chinese: "数据字典", traditional: "數據字典" },
    { japanese: "データセット", furigana: "データセット", english: "dataset", chinese: "数据集", traditional: "數據集" },
    { japanese: "データベース", furigana: "データベース", english: "database", chinese: "数据库", traditional: "數據庫" }
  ],
  "な行": [
    { japanese: "認可", furigana: "にんか", english: "authorization", chinese: "授权", traditional: "授權" },
    { japanese: "認証", furigana: "にんしょう", english: "authentication", chinese: "验证", traditional: "驗證" },
    { japanese: "認証サービス", furigana: "にんしょうサービス", english: "authentication service", chinese: "验证服务", traditional: "驗證服務" },
    { japanese: "ネットワーク", furigana: "ネットワーク", english: "network", chinese: "网络", traditional: "網絡" },
    { japanese: "ネットワークアドレス", furigana: "ネットワークアドレス", english: "network address", chinese: "网络地址", traditional: "網絡地址" },
    { japanese: "ネットワークカード", furigana: "ネットワークカード", english: "network card", chinese: "网卡", traditional: "網卡" },
    { japanese: "ネットワークフロー", furigana: "ネットワークフロー", english: "network flow", chinese: "网络流", traditional: "網絡流" },
    { japanese: "ノード", furigana: "ノード", english: "node", chinese: "节点", traditional: "節點" }
  ],
  "は行": [
  { japanese: "ハードウェア", furigana: "ハードウェア", english: "hardware", chinese: "硬件", traditional: "硬件" },
  { japanese: "バーンダウンチャート", furigana: "バーンダウンチャート", english: "burndown chart", chinese: "燃尽图", traditional: "燃盡圖" },
  { japanese: "バイト", furigana: "バイト", english: "byte", chinese: "字节", traditional: "字節" },
  { japanese: "ハイパーリンク", furigana: "ハイパーリンク", english: "hyperlink", chinese: "超链接", traditional: "超鏈接" },
  { japanese: "パイプライン処理", furigana: "パイプラインしょり", english: "pipeline", chinese: "流水线、管线", traditional: "流水線、管線" },
  { japanese: "バックアップ", furigana: "バックアップ", english: "backup", chinese: "备份", traditional: "備份" },
  { japanese: "バックアップファイル", furigana: "バックアップファイル", english: "backup file", chinese: "备份文件", traditional: "備份文件" },
  { japanese: "パッケージ", furigana: "パッケージ", english: "package", chinese: "包", traditional: "包" },
  { japanese: "パッケージ処理", furigana: "パッケージしょり", english: "packaging", chinese: "打包", traditional: "打包" },
  { japanese: "バッチ処理", furigana: "バッチしょり", english: "batch processing", chinese: "批处理", traditional: "批處理" },
  { japanese: "ハフマン符号", furigana: "ハフマンふごう", english: "Huffman coding", chinese: "霍夫曼编码", traditional: "霍夫曼編碼" },
  { japanese: "パレート図", furigana: "パレートず", english: "Pareto chart", chinese: "帕累托图、排列图法、主次因素分析法", traditional: "帕累托圖、排列圖法、主次因素分析法" },
  { japanese: "パンくずリスト", furigana: "パンくずリスト", english: "breadcrumb list", chinese: "面包屑导航", traditional: "麵包屑導航" },
  { japanese: "ハンドラ", furigana: "ハンドラ", english: "handler", chinese: "处理器", traditional: "處理器" },
  { japanese: "ヒープ領域", furigana: "ヒープりょういき", english: "heap memory", chinese: "堆内存", traditional: "堆內存" },
  { japanese: "ビット", furigana: "ビット", english: "bit", chinese: "比特", traditional: "比特" },
  { japanese: "ビュー", furigana: "ビュー", english: "view", chinese: "视图", traditional: "視圖" },
  { japanese: "ファイアウォール", furigana: "ファイアウォール", english: "firewall", chinese: "防火墙", traditional: "防火牆" },
  { japanese: "ファジング", furigana: "ファジング", english: "fuzzing", chinese: "模糊测试", traditional: "模糊測試" },
  { japanese: "ファンクションポイント法", furigana: "ファンクションポイントほう", english: "function point method", chinese: "功能点法", traditional: "功能點法" },
  { japanese: "フラッシュメモリ", furigana: "フラッシュメモリ", english: "flash memory", chinese: "闪存、快闪存储器", traditional: "閃存、快閃存儲器" },
  { japanese: "プリエンプション", furigana: "プリエンプション", english: "preemption", chinese: "抢占式多任务处理", traditional: "搶占式多任務處理" },
  { japanese: "ブルートフォース攻撃", furigana: "ブルートフォースこうげき", english: "brute force attack", chinese: "蛮力攻击", traditional: "蠻力攻擊" },
  { japanese: "プレシデンスダイアグラム法", furigana: "プレシデンスダイアグラムほう", english: "presence diagramming", chinese: "前导图法", traditional: "前導圖法" },
  { japanese: "プレフィックス", furigana: "プレフィックス", english: "prefix", chinese: "前缀", traditional: "前綴" },
  { japanese: "ブロードキャストアドレス", furigana: "ブロードキャストアドレス", english: "broadcast address", chinese: "广播地址", traditional: "廣播地址" },
  { japanese: "プロキシサーバ", furigana: "プロキシサーバ", english: "proxy server", chinese: "代理服务器", traditional: "代理服務器" },
  { japanese: "プログラミング", furigana: "プログラミング", english: "programming", chinese: "编程、程序设计", traditional: "編程、程序設計" },
  { japanese: "プログラム", furigana: "プログラム", english: "program", chinese: "程序", traditional: "程序" },
  { japanese: "プログラムカウンタ", furigana: "プログラムカウンタ", english: "program counter", chinese: "程序计数器", traditional: "程序計數器" },
  { japanese: "プロセス", furigana: "プロセス", english: "process", chinese: "进程", traditional: "進程" },
  { japanese: "プロトコル", furigana: "プロトコル", english: "protocol", chinese: "协议", traditional: "協議" },
  { japanese: "プロファイラ", furigana: "プロファイラ", english: "profiler", chinese: "性能解析工具", traditional: "性能解析工具" },
  { japanese: "分散クエリ", furigana: "ぶんさんクエリ", english: "distributed query", chinese: "分布式查询", traditional: "分佈式查詢" },
  { japanese: "分散コンピューティング", furigana: "ぶんさんコンピューティング", english: "distributed computing", chinese: "分布式计算", traditional: "分佈式計算" },
  { japanese: "並列接続", furigana: "へいれつせつぞく", english: "parallel connection", chinese: "并联", traditional: "並聯" },
  { japanese: "ホストアドレス", furigana: "ホストアドレス", english: "host address", chinese: "主机地址", traditional: "主機地址" },
  { japanese: "ホットキー", furigana: "ホットキー", english: "hot key", chinese: "热键", traditional: "熱鍵" }
],
"ま行": [
  { japanese: "マージソート", furigana: "マージソート", english: "merge sort", chinese: "归并排序", traditional: "歸併排序" },
  { japanese: "マウス", furigana: "マウス", english: "mouse", chinese: "鼠标", traditional: "鼠標" },
  { japanese: "マクロ", furigana: "マクロ", english: "macro", chinese: "宏", traditional: "宏" },
  { japanese: "マクロウィルス", furigana: "マクロウィルス", english: "macro virus", chinese: "宏病毒", traditional: "宏病毒" },
  { japanese: "マスク", furigana: "マスク", english: "mask", chinese: "掩码", traditional: "掩碼" },
  { japanese: "マルチタスク", furigana: "マルチタスク", english: "multi-tasking", chinese: "多任务", traditional: "多任務" },
  { japanese: "マルチユーザー", furigana: "マルチユーザー", english: "multiuser", chinese: "多用户", traditional: "多用戶" }
],
"や行": [
  { japanese: "有限オートマトン", furigana: "ゆうげんオートマトン", english: "finite automata", chinese: "有限自动机、时序机", traditional: "有限自動機、時序機" },
  { japanese: "読み書き", furigana: "よみかき", english: "read and write", chinese: "读写", traditional: "讀寫" }
],
"ら行": [
  { japanese: "ライブマイグレーション", furigana: "ライブマイグレーション", english: "live migration", chinese: "实时迁移", traditional: "實時遷移" },
  { japanese: "ラウンドロビン", furigana: "ラウンドロビン", english: "Round-Robin", chinese: "轮询调度", traditional: "輪詢調度" },
  { japanese: "ランサムウェア", furigana: "ランサムウェア", english: "ransomware", chinese: "勒索软件", traditional: "勒索軟件" },
  { japanese: "リエントラント、再入可能", furigana: "リエントラント、さいにゅうかのう", english: "reentrant , re-entrant", chinese: "可重入", traditional: "可重入" },
  { japanese: "リカーシブ、再帰", furigana: "リカーシブ、さいき", english: "recursive", chinese: "递归", traditional: "遞歸" },
  { japanese: "リグレッションテスト、 回帰テスト", furigana: "リグレッションテスト、かいきテスト", english: "regression test", chinese: "回归测试", traditional: "回歸測試" },
  { japanese: "リスクベース認証", furigana: "リスクベースにんしょう", english: "risk-based authentication", chinese: "基于风险的认证", traditional: "基於風險的認證" },
  { japanese: "リゾルバ", furigana: "リゾルバ", english: "resolver", chinese: "解析器", traditional: "解析器" },
  { japanese: "リトルエンディアン", furigana: "リトルエンディアン", english: "little endian", chinese: "小端序、小尾序", traditional: "小端序、小尾序" },
  { japanese: "リバースプロキシサーバ", furigana: "リバースプロキシサーバ", english: "reverse proxy server", chinese: "反向代理服务器", traditional: "反向代理服務器" },
  { japanese: "リモート、遠隔", furigana: "リモート、えんかく", english: "remote", chinese: "远程", traditional: "遠程" },
  { japanese: "隣接行列", furigana: "りんせつぎょうれつ", english: "adjacency matrix", chinese: "邻接矩阵", traditional: "鄰接矩陣" },
  { japanese: "ルータ", furigana: "ルータ", english: "router", chinese: "路由器", traditional: "路由器" },
  { japanese: "ループ", furigana: "ループ", english: "loop", chinese: "循环", traditional: "循環" },
  { japanese: "レインボーテーブル", furigana: "レインボーテーブル", english: "rainbow table", chinese: "彩虹表", traditional: "彩虹表" },
  { japanese: "レジスタ", furigana: "レジスタ", english: "register", chinese: "寄存器", traditional: "寄存器" },
  { japanese: "レンダリング", furigana: "レンダリング", english: "rendering", chinese: "渲染、着色", traditional: "渲染、著色" },
  { japanese: "ロールバック", furigana: "ロールバック", english: "rollback", chinese: "回滚、后滚", traditional: "回滾、後滾" },
  { japanese: "ロールフォワード", furigana: "ロールフォワード", english: "roll forward", chinese: "前滚", traditional: "前滾" },
  { japanese: "ログ", furigana: "ログ", english: "log", chinese: "日志", traditional: "日誌" },
  { japanese: "ログイン", furigana: "ログイン", english: "login", chinese: "登录", traditional: "登錄" }
],
"わ行": [
  { japanese: "ワークアラウンド", furigana: "ワークアラウンド", english: "workaround", chinese: "解决方法", traditional: "解決方法" },
  { japanese: "ワークパッケージ", furigana: "ワークパッケージ", english: "work package", chinese: "工作包", traditional: "工作包" },
  { japanese: "ワークフロー", furigana: "ワークフロー", english: "workflow", chinese: "工作流", traditional: "工作流" },
  { japanese: "ワイヤフレーム表現", furigana: "ワイヤフレームひょうげん", english: "wireframe model", chinese: "线框模型", traditional: "線框模型" }
]

}